version: '3.8'

services:
  # MySQL Container
  mysql:
    image: mysql:5.6
    container_name: orange-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: orange1
      MYSQL_DATABASE: orange1
      MYSQL_USER: orange1
      MYSQL_PASSWORD: orange1
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      #- ./"name of the.sql":/docker-entrypoint-initdb.d/backup.sql
  # Your Application Container
  app:
    image: orange:latest
    container_name: orange-container
    restart: always
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - "80:80"
    volumes:
      - app-data:/var/www/html

volumes:
  mysql-data:
  app-data:
