name: OrangeHrm CI/CD

on:
  push:
    branches:
        - 5.1-EC2-Docker
jobs: 
  SSH-into-instance:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
       - name: Checkout Repository
         uses: actions/checkout@v2
         
       - name: Set up AWS CLI
         uses: aws-actions/configure-aws-credentials@v2
         with:
             role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
             role-duration-seconds: 3600
             aws-region: us-east-1
             
             
       - name: Get SSH private key from Parameter Store
         id: get-ssh-key
         run: |
          SSH_PRIVATE_KEY=$(aws ssm get-parameter --name "private-key" --query "Parameter.Value" --output text)
          echo "::set-output name=ssh_private_key::$SSH_PRIVATE_KEY"

       - name: Get public IP (DNS) from Parameter Store
         id: get-public-ip
         run: |
          REMOTE_HOST=$(aws ssm get-parameter --name "MyPublicIPAddress" --query "Parameter.Value" --output text)
          echo "::set-output name=MyPublicIPAddress::$REMOTE_HOST" 
          
       - name: Prepare private key
         run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 400 private_key.pem
          cat private_key.pem  # For troubleshooting purposes, check the key content

       - name: SSH into EC2 Instance
         env:
          PRIVATE_KEY_PATH: private_key.pem
          REMOTE_HOST: ${{ steps.get-public-ip.outputs.public_ip }}
          REMOTE_USER: ubuntu
         run: |
           (ssh -i private_key.pem -o "StrictHostKeyChecking=no" "$REMOTE_USER@$REMOTE_HOST" '
            git clone https://github.com/SkyOps-Dev/orangehrm.git
            cd orangehrm
            git checkout remotes/origin/5.1-EC2-Docker
            sudo apt-get update
            sudo apt-get install ca-certificates curl gnupg
            sudo install -m 0755 -d /etc/apt/keyrings
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
            sudo chmod a+r /etc/apt/keyrings/docker.gpg
            echo \
            "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
            "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            sudo apt-get update
            sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
            sudo docker build -t orange .
            sudo docker images
          ')
          
       - name: Deploy Application & Database
         env:
          SSH_PRIVATE_KEY: ${{ steps.get-ssh-key.outputs.ssh_private_key }}
          REMOTE_HOST: ${{ steps.get-public-ip.outputs.MyPublicIPAddress }}
          REMOTE_USER: ubuntu
         run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$REMOTE_HOST" >> ~/.ssh/known_hosts
          (ssh -i ~/.ssh/id_rsa -o "StrictHostKeyChecking=no" "$REMOTE_USER@$REMOTE_HOST" '
            cd orangehrm
            sudo docker compose up -d
            sudo docker ps
          ')
