name: OrangeHrm CI/CD

on:
  push:
    branches:
        - 5.1-EC2-Docker
jobs: 
  SSH-into-instance:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
       - name: Checkout Repository
         uses: actions/checkout@v2
         
       - name: Set up AWS CLI
         uses: aws-actions/configure-aws-credentials@v2
         with:
             role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
             role-duration-seconds: 3600
             aws-region: us-east-1
          
       - name: Retrieve Public IP from Parameter Store
         run: |
          PUBLIC_IP=$(aws ssm get-parameter --name "MyPublicIPAddress" --query "Parameter.Value" --output text)
          echo "Retrieved Public IP:"
          echo "$PUBLIC_IP"
          echo "REMOTE_HOST=$PUBLIC_IP" >> $GITHUB_ENV

       - name: Retrieve Private Key from Parameter Store
         run: |
          PRIVATE_KEY=$(aws ssm get-parameter --name "private-key" --query "Parameter.Value" --output text)
          echo "Retrieved Private Key:"
          echo "$PRIVATE_KEY"
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" | tr -d '\r' > ~/.ssh/private_key
          cat ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key

       - name: SSH into EC2 Instance
         run: |
          REMOTE_HOST=$REMOTE_HOST
          ssh-keyscan -H "$REMOTE_HOST" >> ~/.ssh/known_hosts
          (ssh -i ~/.ssh/private_key -o "StrictHostKeyChecking=no" "ubuntu@$REMOTE_HOST" '
            echo "Connected to the instance."
            git clone https://github.com/SkyOps-Dev/orangehrm.git
            cd orangehrm
            git checkout remotes/origin/5.1-EC2-Docker
            sudo apt-get update
            sudo apt-get install ca-certificates curl gnupg
            sudo install -m 0755 -d /etc/apt/keyrings
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
            sudo chmod a+r /etc/apt/keyrings/docker.gpg
            echo \
            "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
            "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            sudo apt-get update
            sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
            sudo docker build -t orange .
            sudo docker images
           ')
          
       - name: Deploy Application & Database
         run: |
          REMOTE_HOST=$REMOTE_HOST
          ssh-keyscan -H "$REMOTE_HOST" >> ~/.ssh/known_hosts
          (ssh -i ~/.ssh/private_key -o "StrictHostKeyChecking=no" "ubuntu@$REMOTE_HOST" '
            cd orangehrm
            sudo docker compose up -d
            sudo docker ps
          ')
